 version: 2.1
 
 orbs:
  win: circleci/windows@2.2.0
 
 jobs:
   build:
     executor: win/default     
     steps:
      - checkout
      - run: 
          name: restore 
          command: dotnet restore CicrleCiDemo/CicrleCiDemo.csproj
     
      - run: 
          name: build project
          command: dotnet build CicrleCiDemo/CicrleCiDemo.csproj
      
   deploy:
     steps:
      - run:
          name: Hello World
          command: |
            ssh haild@115.73.217.80 deploy.sh
         
 workflows:
   version: 2
   my_workflows:
    jobs:
     - build
     - deploy:
         requires:
           - build
