 version: 2.1
 
 orbs:
  win: circleci/windows@2.2.0
 
 jobs:
   check_out_code:
     executor: win/default     
     steps:
      - checkout
      
      
   build_code:
     executor: win/default     
     steps:
      - run: 
          name: restore 
          command: dotnet restore CicrleCiDemo/CicrleCiDemo.csproj
     
      - run: 
          name: build project
          command: dotnet build CicrleCiDemo/CicrleCiDemo.csproj
         
 workflows:
   version: 2
   my_workflows:
    jobs:
     - check_out_code
     - build_code
